name: First GitHub Action
on:
  push:
    branches:
      - master


jobs: 
  example-job:
    runs-on: ubuntu-latest 

    steps:
      - name: Welcoming
        run: echo "Hello From Git Hub Action"

      - name: checkout repositry 
        uses: actions/checkout@v4.2.2

      - name: PWD LS
        run: |
             pwd
             ls -laF


        
      
