on:
    workflow_dispatch: 
        inputs:
            enviroment:
                description: Choose Enviroment
                required: true
                default: staging 
                type: choice
                options:
                    - staging 
                    - production
                    - testing 



jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy Application
              run: echo "Deployed ${{ inputs.enviroment }}"