name: Pull Rerquest workflow
on: 
    pull_request: 
        branches: 
            - master
            - "release/**"

        
        paths: 
            - "src/**"


    push:
        branches: 
            - master
            - "release/**"

        paths: 
            - "src/**"

jobs:

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Run NPM Test 
              run: npm test